/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Janelas;

import DAO.ClienteDao;
import DAO.VendedorDAO;
import LDXPS.Cliente;
import LDXPS.Vendedor;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class Cad_Vendedor extends javax.swing.JFrame {

    int controle;
    Vendedor vendAnt;
   
    public Cad_Vendedor() {
        initComponents();
        this.controle = 0;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.but_excluir.setEnabled(false);
        this.setTitle("Cadastro Vendedor");
        
        ClienteDao cDao = new ClienteDao();
        
        int iterator = 0;
        for(Cliente cli: cDao.select()){
            DefaultTableModel model = (DefaultTableModel) this.tabela_clientes.getModel();
            model.addRow(new Object[]{});
            
            this.tabela_clientes.getModel().setValueAt(cli.getDsnome(), iterator, 0);
            iterator++;
        }
    }
    
    public Cad_Vendedor(Vendedor vend){
        this.vendAnt = vend;
        this.controle = 1;
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
        ClienteDao cli = new ClienteDao();
        int iterator = 0;
        for(Cliente cliente: cli.select()){
            DefaultTableModel model = (DefaultTableModel) this.tabela_clientes.getModel();
            

            if(cliente.getVendedor().getDsnome().equals(vend.getDsnome())){
                model.addRow(new Object[]{});
                this.tabela_clientes.getModel().setValueAt(cliente.getDsnome(), iterator, 0);
                iterator++;
            }
        }
        
        this.nome_field.setText(vend.getDsnome());
        this.data_field.setText(vend.getDtnasc());
        this.cod_tab_field.setText(Integer.toString(vend.getCdtab()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_clientes = new javax.swing.JTable();
        nome_field = new javax.swing.JTextField();
        cod_tab_field = new javax.swing.JTextField();
        data_field = new javax.swing.JFormattedTextField();
        but_confirmar = new javax.swing.JButton();
        but_excluir = new javax.swing.JButton();
        but_cria_cliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro Vendedor");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Cod. Tabela Preço:");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("Data Nascimento:");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("Clientes:");

        tabela_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ));
        jScrollPane1.setViewportView(tabela_clientes);

        try {
            data_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        data_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_fieldActionPerformed(evt);
            }
        });

        but_confirmar.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        but_confirmar.setText("Confirmar");
        but_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_confirmarActionPerformed(evt);
            }
        });

        but_excluir.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        but_excluir.setText("Excluir");
        but_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_excluirActionPerformed(evt);
            }
        });

        but_cria_cliente.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        but_cria_cliente.setText("Criar Cliente");
        but_cria_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_cria_clienteActionPerformed(evt);
            }
        });

        jLabel6.setText("aaaa-mm-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cod_tab_field, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(data_field, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(nome_field, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(but_confirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(but_excluir)
                                .addGap(86, 86, 86)
                                .addComponent(but_cria_cliente))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nome_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cod_tab_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(data_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(25, 25, 25)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_confirmar)
                    .addComponent(but_excluir)
                    .addComponent(but_cria_cliente))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void data_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_fieldActionPerformed

    private void but_cria_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_cria_clienteActionPerformed
        this.dispose();
        Cad_Cliente cadastro = new Cad_Cliente();
    }//GEN-LAST:event_but_cria_clienteActionPerformed

    private void but_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_confirmarActionPerformed
        
        
        if(this.controle == 1){
            Vendedor vend = new Vendedor();
            vend.setCdvend(this.vendAnt.getCdvend());
            if(nome_field.getText().equals("") || cod_tab_field.getText().equals("") || data_field.getText().equals("    -  -  ")){
            JOptionPane.showMessageDialog(null,"Preencha todos os campos!");
            }else{
                vend.setDsnome(nome_field.getText());
                vend.setDtnasc(data_field.getText());
                vend.setCdtab(Integer.parseInt(cod_tab_field.getText()));
                VendedorDAO dao = new VendedorDAO();
                    if(dao.update(vend)){
                    JOptionPane.showMessageDialog(null,"Dados atualizados com sucesso!");
                         nome_field.setText("");
                         data_field.setText("");
                         cod_tab_field.setText("");
                         this.but_excluir.setEnabled(false);
                         this.controle = 0;
                    }else{
                         JOptionPane.showMessageDialog(null,null, "Erro ao atualizar!", JOptionPane.ERROR_MESSAGE);
                    }
            
            }
        }else{
        Vendedor vend = new Vendedor();
        UUID uuid = UUID.randomUUID();
        String struuid = uuid.toString();
        
        if(nome_field.getText().equals("") || cod_tab_field.getText().equals("") || data_field.getText().equals("    -  -  ")){
           JOptionPane.showMessageDialog(null,"Preencha todos os campos!");
            }else{
             vend.setDsnome(nome_field.getText());
             vend.setDtnasc(data_field.getText());
             vend.setCdtab(Integer.parseInt(cod_tab_field.getText()));
             vend.setCdvend(struuid);
             VendedorDAO vendedor = new VendedorDAO();
                if(vendedor.insert(vend)){
                    JOptionPane.showMessageDialog(null,"Vendedor cadastrado com sucesso!");
                    nome_field.setText("");
                    data_field.setText("");
                    cod_tab_field.setText("");
                }else{
                    JOptionPane.showMessageDialog(null,null, "Erro ao cadastrar!", JOptionPane.ERROR_MESSAGE);
              }
          }
        }
        this.dispose();
        Home home = new Home();
    }//GEN-LAST:event_but_confirmarActionPerformed

    private void but_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_excluirActionPerformed
        Vendedor vendedor = new Vendedor();
        vendedor = this.vendAnt;
        int i = 0;
        ClienteDao dao = new ClienteDao();
        String novoVend = null;
        while(i == 0){
            VendedorDAO venDao = new VendedorDAO();
            novoVend = venDao.aleat();
            if(novoVend.equals(vendedor.getCdvend())){
                i = 0;
            }else{
                i = 1;
            }
        }    
        
        
        for(Cliente cliente : dao.select()){
           if(cliente.getVendedor().getCdvend().equals(vendedor.getCdvend())){
               cliente.getVendedor().setCdvend(novoVend);
               ClienteDao cdao = new ClienteDao();
               if(cdao.update(cliente)){
                   
               }
           }
        }
        VendedorDAO vdao = new VendedorDAO();
        if(vdao.apaga(vendedor)){
            JOptionPane.showMessageDialog(null,"Vendedor deletado com sucesso!");
            nome_field.setText("");
            data_field.setText("");
            cod_tab_field.setText("");
            this.but_excluir.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(null,null, "Erro ao deletar!", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_but_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_Vendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_confirmar;
    private javax.swing.JButton but_cria_cliente;
    private javax.swing.JButton but_excluir;
    private javax.swing.JTextField cod_tab_field;
    private javax.swing.JFormattedTextField data_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nome_field;
    private javax.swing.JTable tabela_clientes;
    // End of variables declaration//GEN-END:variables
}
