/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Janelas;

import DAO.ClienteDao;
import DAO.VendedorDAO;
import LDXPS.Cliente;
import LDXPS.Vendedor;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class Cad_Cliente extends javax.swing.JFrame {

    Vendedor vend;
    int controle;
    Cliente cli;
    
    public Cad_Cliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.controle = 0;
        this.but_excluir.setEnabled(false);
        this.setTitle("Cadastro Cliente");
        
         VendedorDAO vendedor = new VendedorDAO();
        int iterator = 0;
        for(Vendedor vend: vendedor.select()){
            DefaultTableModel model = (DefaultTableModel) this.tabela_vendedores.getModel();
            model.addRow(new Object[]{});
            
            this.tabela_vendedores.getModel().setValueAt(vend.getCdvend(), iterator, 0);
            this.tabela_vendedores.getModel().setValueAt(vend.getDsnome(), iterator, 1);
            this.tabela_vendedores.getModel().setValueAt(vend.getCdtab(), iterator, 2);
            this.tabela_vendedores.getModel().setValueAt(vend.getDtnasc(), iterator, 3);
            iterator++;
        }
        
    }
    public Cad_Cliente(Cliente cli){
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.controle = 1;
        this.cli = cli;
        
        this.nome_field.setText(cli.getDsnome());
        this.tipo_pessoa_cbox.setSelectedItem(cli.getIdtipo());
        this.limite_credito_field.setText(Double.toString(cli.getDslim()));
         VendedorDAO vendedor = new VendedorDAO();

         int iterator = 0;
        for(Vendedor vend: vendedor.select()){
            DefaultTableModel model = (DefaultTableModel) this.tabela_vendedores.getModel();
            model.addRow(new Object[]{});
            
            this.tabela_vendedores.getModel().setValueAt(vend.getCdvend(), iterator, 0);
            this.tabela_vendedores.getModel().setValueAt(vend.getDsnome(), iterator, 1);
            this.tabela_vendedores.getModel().setValueAt(vend.getCdtab(), iterator, 2);
            this.tabela_vendedores.getModel().setValueAt(vend.getDtnasc(), iterator, 3);
            iterator++;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        but_confirmar = new javax.swing.JButton();
        but_excluir = new javax.swing.JButton();
        but_cria_vendedor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nome_field = new javax.swing.JTextField();
        limite_credito_field = new javax.swing.JTextField();
        tipo_pessoa_cbox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_vendedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(649, 510));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Cadastro Cliente");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Tipo de Pessoa:");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("Limite de Crédito:");

        but_confirmar.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        but_confirmar.setText("Confirmar");
        but_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_confirmarActionPerformed(evt);
            }
        });

        but_excluir.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        but_excluir.setText("Excluir");
        but_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_excluirActionPerformed(evt);
            }
        });

        but_cria_vendedor.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        but_cria_vendedor.setText("Criar Vendedor");
        but_cria_vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_cria_vendedorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("Vendedor:");

        limite_credito_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limite_credito_fieldActionPerformed(evt);
            }
        });

        tipo_pessoa_cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PF", "PJ" }));

        tabela_vendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CDVEND", "DSNOME", "CDTAB", "DTNASC"
            }
        ));
        tabela_vendedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_vendedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_vendedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome_field, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipo_pessoa_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(limite_credito_field, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(but_confirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(but_excluir)
                        .addGap(147, 147, 147)
                        .addComponent(but_cria_vendedor))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nome_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tipo_pessoa_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(limite_credito_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_excluir)
                    .addComponent(but_confirmar)
                    .addComponent(but_cria_vendedor))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_cria_vendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_cria_vendedorActionPerformed
            this.dispose();
            Cad_Vendedor vend = new Cad_Vendedor();
    }//GEN-LAST:event_but_cria_vendedorActionPerformed

    private void limite_credito_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limite_credito_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limite_credito_fieldActionPerformed

    private void but_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_confirmarActionPerformed
       
          if(this.controle == 1){
           Cliente cliente = new Cliente();
           cliente.setCdcl(this.cli.getCdcl());
           int indiceLinha = tabela_vendedores.getSelectedRow();
           String codvend = tabela_vendedores.getValueAt(indiceLinha,0).toString();
           Vendedor vendedor = new Vendedor();
           vendedor.setCdvend(codvend);
           ClienteDao dao = new ClienteDao();
           
            if(nome_field.getText().equals("") || limite_credito_field.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Preencha todos os campos!");
            }else{
                cliente.setDsnome(nome_field.getText());
                cliente.setDslim(Double.parseDouble(limite_credito_field.getText()));
                cliente.setIdtipo(tipo_pessoa_cbox.getSelectedItem().toString());
                cliente.setVendedor(vendedor);
                if(dao.update(cliente)){
                    JOptionPane.showMessageDialog(null,"Dados atualizados com sucesso!");
                    nome_field.setText("");
                    limite_credito_field.setText("");
                    this.but_excluir.setEnabled(false);
                    this.controle = 0;
                }else{
                    JOptionPane.showMessageDialog(null,null, "Erro ao atualizar!", JOptionPane.ERROR_MESSAGE);
                }
            }
       }else{
      
           Cliente cliente = new Cliente();
           UUID uuid = UUID.randomUUID();
           String struuid = uuid.toString();
            if(limite_credito_field.getText().equals("") || nome_field.getText().equals("") || this.vend == null){
                         JOptionPane.showMessageDialog(null,"Preencha todos os campos!");

            }else{
              cliente.setCdcl(struuid);
              cliente.setDslim(Double.parseDouble(limite_credito_field.getText()));
              cliente.setDsnome(nome_field.getText());
              cliente.setIdtipo(tipo_pessoa_cbox.getSelectedItem().toString());
              cliente.setVendedor(this.vend);
            
              ClienteDao cDao = new ClienteDao();
            
               if(cDao.insert(cliente)){
                    JOptionPane.showMessageDialog(null,"Cliente cadastrado com sucesso!");
                    limite_credito_field.setText("");
                 nome_field.setText("");
              }else{
                 JOptionPane.showMessageDialog(null,null, "Erro ao cadastrar!", JOptionPane.ERROR_MESSAGE);
                
             }
            } 
          
          }
        this.dispose();
        Home home = new Home();
    }//GEN-LAST:event_but_confirmarActionPerformed

    private void tabela_vendedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_vendedoresMouseClicked
        int indiceLinha = tabela_vendedores.getSelectedRow();
        Vendedor vend = new Vendedor();
        vend.setCdvend(tabela_vendedores.getValueAt(indiceLinha,0).toString());
        vend.setDsnome(tabela_vendedores.getValueAt(indiceLinha,1).toString());
        vend.setCdtab(Integer.parseInt(tabela_vendedores.getValueAt(indiceLinha,2).toString()));
        vend.setDtnasc(tabela_vendedores.getValueAt(indiceLinha, 3).toString());
        
        this.vend = vend;
    }//GEN-LAST:event_tabela_vendedoresMouseClicked

    private void but_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_excluirActionPerformed
       ClienteDao dao = new ClienteDao();
       if(dao.apaga(this.cli)){
           JOptionPane.showMessageDialog(null,"Cliente removido com sucesso!");
           limite_credito_field.setText("");
           nome_field.setText("");
           this.but_excluir.setEnabled(false);
           this.controle = 0;
       }else{
           JOptionPane.showMessageDialog(null,null, "Erro ao remover!", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_but_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_confirmar;
    private javax.swing.JButton but_cria_vendedor;
    private javax.swing.JButton but_excluir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField limite_credito_field;
    private javax.swing.JTextField nome_field;
    private javax.swing.JTable tabela_vendedores;
    private javax.swing.JComboBox<String> tipo_pessoa_cbox;
    // End of variables declaration//GEN-END:variables
}
