
/*Código feito por Lucas Rossi Rabelo
    Primeira versão, contém pequenos defeitos, mas é completamente funcional
*/
package Janelas;
import Conexao.ConectaBD;
import DAO.*;
import LDXPS.Cliente;
import LDXPS.Vendedor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Home extends javax.swing.JFrame {
    
        String nome_vend;
        String nome_cliente;
        
    public Home() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle("Home");
        
        VendedorDAO vendedor = new VendedorDAO();
        int iterator = 0;
        for(Vendedor vend: vendedor.select()){
            DefaultTableModel model = (DefaultTableModel) this.tabela_vendedores.getModel();
            model.addRow(new Object[]{});
            
            this.tabela_vendedores.getModel().setValueAt(vend.getDsnome(), iterator, 0);
            iterator++;
        }
               
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_clientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_vendedores = new javax.swing.JTable();
        but_cria_vendedor = new javax.swing.JButton();
        but_edita_vendedor = new javax.swing.JButton();
        but_cria_cliente = new javax.swing.JButton();
        but_edita_cliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        but_todos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Vendedores:");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Clientes:");

        tabela_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tipo Pessoa", "Limite de Crédito"
            }
        ));
        tabela_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_clientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_clientes);
        if (tabela_clientes.getColumnModel().getColumnCount() > 0) {
            tabela_clientes.getColumnModel().getColumn(1).setPreferredWidth(15);
        }

        tabela_vendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Vendedor"
            }
        ));
        tabela_vendedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_vendedoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela_vendedores);

        but_cria_vendedor.setFont(new java.awt.Font("NanumGothicExtraBold", 0, 11)); // NOI18N
        but_cria_vendedor.setText("Criar Vendedor");
        but_cria_vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_cria_vendedorActionPerformed(evt);
            }
        });

        but_edita_vendedor.setFont(new java.awt.Font("NanumGothicExtraBold", 0, 11)); // NOI18N
        but_edita_vendedor.setText("Editar Vendedor");
        but_edita_vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_edita_vendedorActionPerformed(evt);
            }
        });

        but_cria_cliente.setFont(new java.awt.Font("NanumGothicExtraBold", 0, 11)); // NOI18N
        but_cria_cliente.setText("Criar Cliente");
        but_cria_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_cria_clienteActionPerformed(evt);
            }
        });

        but_edita_cliente.setFont(new java.awt.Font("NanumGothicExtraBold", 0, 11)); // NOI18N
        but_edita_cliente.setText("Editar Cliente");
        but_edita_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_edita_clienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecione uma das opções abaixo:");

        jLabel4.setText("Selecione uma das opções abaixo:");

        but_todos.setFont(new java.awt.Font("NanumGothicExtraBold", 0, 11)); // NOI18N
        but_todos.setText("Todos");
        but_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_todosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(but_cria_vendedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(but_edita_vendedor))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(but_cria_cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(but_todos)
                        .addGap(91, 91, 91)
                        .addComponent(but_edita_cliente)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(196, 196, 196))))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_cria_vendedor)
                    .addComponent(but_edita_vendedor)
                    .addComponent(but_cria_cliente)
                    .addComponent(but_edita_cliente)
                    .addComponent(but_todos))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_cria_vendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_cria_vendedorActionPerformed
        this.dispose();
        Cad_Vendedor cad = new Cad_Vendedor();
    }//GEN-LAST:event_but_cria_vendedorActionPerformed

    private void but_edita_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_edita_clienteActionPerformed
        if(this.nome_cliente.equals("")){
            JOptionPane.showMessageDialog(null,"Selecione um cliente para editar!"); 
        }else{
        this.dispose();
        Cliente cli = new Cliente();
        cli.setDsnome(this.nome_cliente);
        
        ClienteDao dao = new ClienteDao();
        
        for(Cliente cliente: dao.select()){
            if(cliente.getDsnome().equals(cli.getDsnome())){
                cli = cliente;
            }
        }
        
        
            Cad_Cliente cad = new Cad_Cliente(cli);
        }
    }//GEN-LAST:event_but_edita_clienteActionPerformed

    private void but_edita_vendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_edita_vendedorActionPerformed
        
        String nome = this.nome_vend;
        if(nome.equals("")){
             JOptionPane.showMessageDialog(null,"Selecione um vendedor para editar!"); 
        }else{
        Vendedor vendedor = new Vendedor();
        VendedorDAO vendDao = new VendedorDAO();
       for(Vendedor vend: vendDao.select()){
            if(vend.getDsnome().equals(nome_vend)){
               
                vendedor.setDsnome(vend.getDsnome());
                vendedor.setCdtab(vend.getCdtab());                
                vendedor.setCdvend(vend.getCdvend());
                vendedor.setDtnasc(vend.getDtnasc());
                               
            }
        }
         Cad_Vendedor cad = new Cad_Vendedor(vendedor);
        }
        this.dispose();
    }//GEN-LAST:event_but_edita_vendedorActionPerformed

    private void but_cria_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_cria_clienteActionPerformed
       this.dispose();
       Cad_Cliente cad = new Cad_Cliente();
    }//GEN-LAST:event_but_cria_clienteActionPerformed

    private void but_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_todosActionPerformed
       DefaultTableModel tabela;
        
        tabela = (DefaultTableModel)this.tabela_clientes.getModel();
        tabela.setNumRows(0);
        
        ClienteDao cli = new ClienteDao();
        int iterator = 0;
        for(Cliente cliente: cli.select()){
            DefaultTableModel model = (DefaultTableModel) this.tabela_clientes.getModel();
            model.addRow(new Object[]{});
            
            this.tabela_clientes.getModel().setValueAt(cliente.getDsnome(), iterator, 0);
            this.tabela_clientes.getModel().setValueAt(cliente.getIdtipo(), iterator, 1);
            this.tabela_clientes.getModel().setValueAt(cliente.getDslim(), iterator , 2);
            iterator++;
        }
    }//GEN-LAST:event_but_todosActionPerformed

    private void tabela_vendedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_vendedoresMouseClicked
        
        DefaultTableModel tabela;
        tabela = (DefaultTableModel)this.tabela_clientes.getModel();
        tabela.setNumRows(0);
        int indiceLinha = tabela_vendedores.getSelectedRow();
        String nome_vend = tabela_vendedores.getValueAt(indiceLinha, 0).toString();
        this.nome_vend = nome_vend;
        
        //System.out.println(nome_vend);
        
        ClienteDao cli = new ClienteDao();
        int iterator = 0;
        for(Cliente cliente: cli.select()){
            DefaultTableModel model = (DefaultTableModel) this.tabela_clientes.getModel();
            
            
            if(cliente.getVendedor().getDsnome().equals(nome_vend)){
                model.addRow(new Object[]{});
                this.tabela_clientes.getModel().setValueAt(cliente.getDsnome(), iterator, 0);
                this.tabela_clientes.getModel().setValueAt(cliente.getIdtipo(), iterator, 1);
                this.tabela_clientes.getModel().setValueAt(cliente.getDslim(), iterator , 2);
                iterator++;
            }
        }
        
    }//GEN-LAST:event_tabela_vendedoresMouseClicked

    private void tabela_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_clientesMouseClicked
        
        int indiceLinha = tabela_clientes.getSelectedRow();
        String nome_cliente = tabela_clientes.getValueAt(indiceLinha, 0).toString();
        this.nome_cliente = nome_cliente;
    }//GEN-LAST:event_tabela_clientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_cria_cliente;
    private javax.swing.JButton but_cria_vendedor;
    private javax.swing.JButton but_edita_cliente;
    private javax.swing.JButton but_edita_vendedor;
    private javax.swing.JButton but_todos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabela_clientes;
    private javax.swing.JTable tabela_vendedores;
    // End of variables declaration//GEN-END:variables
}
